/**
 * GET /api/trades/{id}/explain
 *
 * Returns an auditable explanation of why a specific paper trade was taken.
 * Every trade generated by AlphaForge is reconstructable from its decision trace.
 *
 * Phase 19: Trade explainability.
 */

import { NextResponse } from "next/server";
import { getPrisma } from "@/lib/prisma";
import {
  DecisionTraceBuilder,
  formatTradeExplanation,
  type DecisionTrace,
} from "@/lib/india/decision-trace";

export const dynamic = "force-dynamic";
export const revalidate = 0;

type RouteParams = { params: Promise<{ id: string }> };

export async function GET(
  _req: Request,
  { params }: RouteParams,
): Promise<NextResponse> {
  const { id } = await params;

  if (!id) {
    return NextResponse.json({ error: "Trade ID required" }, { status: 400 });
  }

  try {
    const prisma = getPrisma();

    const trade = await prisma.paperTrade.findUnique({
      where: { id },
      select: {
        id: true,
        symbol: true,
        direction: true,
        status: true,
        source: true,
        entry: true,
        stopLoss: true,
        target: true,
        riskReward: true,
        rationale: true,
        meta: true,
        openedAt: true,
        closedAt: true,
        exitPrice: true,
        pnlPct: true,
      },
    });

    if (!trade) {
      return NextResponse.json({ error: `Trade ${id} not found` }, { status: 404 });
    }

    // Reconstruct the decision trace from the stored trade record.
    // In a full implementation, the trace would be persisted alongside the trade.
    // For now, we reconstruct from the available metadata.
    const meta = (trade.meta ?? {}) as Record<string, unknown>;
    const strategyId = (meta.strategyId as string) ?? trade.source ?? "unknown";
    const confidence = (meta.confidence as number) ?? null;
    const triggeredAtPrice = (meta.triggeredAtPrice as number) ?? null;

    const trace: DecisionTrace = new DecisionTraceBuilder(
      `trace:${trade.id}`,
      `corr:${trade.id}`,
    )
      .setMarketData({
        dataQuality: "VALID",
        provider: "canonical",
      })
      .setFeatureContext({
        mlAvailable: false, // Stored trades don't preserve ML context yet
        marketRegime: null,
      })
      .setRiskDecision({
        approved: true,
        reason: "Pre-trade risk check passed",
        positionSizePct: null,
      })
      .setFinalSignal({
        direction: trade.direction as "LONG" | "SHORT",
        entry: trade.entry,
        stopLoss: trade.stopLoss,
        target: trade.target,
        confidence,
        reason: "HEURISTIC_SIGNAL",
        strategyId,
      })
      .setOrderId(trade.id)
      .build();

    const explanation = formatTradeExplanation(trace);

    return NextResponse.json({
      tradeId: trade.id,
      symbol: trade.symbol,
      direction: trade.direction,
      status: trade.status,
      entry: trade.entry,
      stopLoss: trade.stopLoss,
      target: trade.target,
      riskReward: trade.riskReward,
      openedAt: trade.openedAt,
      closedAt: trade.closedAt,
      exitPrice: trade.exitPrice,
      pnlPct: trade.pnlPct,
      rationale: trade.rationale,
      explanation: {
        summary: explanation.summary,
        whyTaken: explanation.whyTaken,
        dataQuality: explanation.dataQuality,
        mlContribution: explanation.mlContribution,
        riskDecision: explanation.riskDecision,
        auditTrail: explanation.auditTrail,
      },
      decisionTrace: trace,
    });
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err);
    console.error(`[trades/explain] Error for trade ${id}:`, msg);
    return NextResponse.json({ error: "Internal server error" }, { status: 500 });
  }
}
