/**
 * Decision Trace — Phase 19
 *
 * Every signal must be reconstructable. This module implements the
 * unified Decision Trace that captures every step of the decision pipeline.
 *
 * The trace answers: WHY WAS THIS TRADE TAKEN?
 *
 * Exposed via: GET /api/trades/{id}/explain
 */

import type { DataQualityStatus } from "./feature-quality-validator";
import type { OptionDataQuality } from "./fno-data-quality";

// ─── Types ───────────────────────────────────────────────────────────────────

export type DecisionReason =
  | "ML_SIGNAL"           // Signal generated by ML model
  | "HEURISTIC_SIGNAL"    // Signal generated by rule-based engine
  | "FALLBACK_SIGNAL"     // ML unavailable; heuristic fallback used
  | "RISK_REJECTED"       // Risk engine blocked the signal
  | "PAPER_ONLY"          // Paper trading mode
  | "FEATURE_INVALID"     // Feature quality too low for ML
  | "CHAIN_DEGRADED";     // Option chain quality degraded

export interface ModelPredictionTrace {
  modelName: string;
  modelVersion: string;
  featureVersion: string;
  prediction: number | string | null;
  confidence: number | null;
  dataQuality: DataQualityStatus;
  invalidFeatureCount: number;
  imputedFeatureCount: number;
  latencyMs: number | null;
}

export interface RiskDecisionTrace {
  approved: boolean;
  reason: string;
  riskScore: number | null;
  probStopHit: number | null;
  probTargetHit: number | null;
  positionSizePct: number | null;
  portfolioUtilization: number | null;
}

export interface DecisionTrace {
  /** Unique ID for this decision trace. Correlates with orderId/tradeId. */
  decisionTraceId: string;
  /** Correlation ID threading through the whole pipeline. */
  correlationId: string | null;
  /** ISO-8601 timestamp when the decision was made. */
  decidedAt: string;

  // ── Market Data Context ──────────────────────────────────────────────────
  marketDataVersion: string | null;
  provider: string | null;
  providerHealth: string | null;
  dataQuality: DataQualityStatus;
  optionChainQuality: OptionDataQuality | null;

  // ── Feature Context ──────────────────────────────────────────────────────
  featureVersion: string | null;
  niftyChangePct: number | null;
  indiaVix: number | null;
  marketRegime: string | null;
  regimeScore: number | null;
  mlAvailable: boolean;

  // ── Model Predictions ────────────────────────────────────────────────────
  modelPredictions: ModelPredictionTrace[];

  // ── Meta Decision ────────────────────────────────────────────────────────
  metaDecision: {
    ensembleScore: number | null;
    calibrationStatus: "CALIBRATED" | "STALE" | "UNAVAILABLE";
    abstentionTriggered: boolean;
    abstentionReason: string | null;
  };

  // ── Risk Decision ────────────────────────────────────────────────────────
  riskDecision: RiskDecisionTrace;

  // ── Position Context ────────────────────────────────────────────────────
  positionContext: {
    currentPositions: number;
    portfolioUtilization: number | null;
    correlatedExposure: number | null;
  };

  // ── Final Signal ────────────────────────────────────────────────────────
  finalSignal: {
    direction: "LONG" | "SHORT" | null;
    entry: number | null;
    stopLoss: number | null;
    target: number | null;
    confidence: number | null;
    reason: DecisionReason;
    strategyId: string | null;
  };

  // ── Order Reference ──────────────────────────────────────────────────────
  orderId: string | null;
  paperMode: boolean;
}

// ─── Builder ─────────────────────────────────────────────────────────────────

export class DecisionTraceBuilder {
  private trace: Partial<DecisionTrace> & { decisionTraceId: string; decidedAt: string };

  constructor(decisionTraceId: string, correlationId?: string) {
    this.trace = {
      decisionTraceId,
      correlationId: correlationId ?? null,
      decidedAt: new Date().toISOString(),
      mlAvailable: false,
      modelPredictions: [],
      dataQuality: "VALID",
      optionChainQuality: null,
      metaDecision: {
        ensembleScore: null,
        calibrationStatus: "UNAVAILABLE",
        abstentionTriggered: false,
        abstentionReason: null,
      },
      riskDecision: {
        approved: false,
        reason: "not evaluated",
        riskScore: null,
        probStopHit: null,
        probTargetHit: null,
        positionSizePct: null,
        portfolioUtilization: null,
      },
      positionContext: {
        currentPositions: 0,
        portfolioUtilization: null,
        correlatedExposure: null,
      },
      finalSignal: {
        direction: null,
        entry: null,
        stopLoss: null,
        target: null,
        confidence: null,
        reason: "HEURISTIC_SIGNAL",
        strategyId: null,
      },
      orderId: null,
      paperMode: true,
    };
  }

  setMarketData(opts: {
    provider?: string;
    providerHealth?: string;
    dataQuality?: DataQualityStatus;
    optionChainQuality?: OptionDataQuality | null;
    marketDataVersion?: string;
  }): this {
    Object.assign(this.trace, {
      provider: opts.provider ?? null,
      providerHealth: opts.providerHealth ?? null,
      dataQuality: opts.dataQuality ?? "VALID",
      optionChainQuality: opts.optionChainQuality ?? null,
      marketDataVersion: opts.marketDataVersion ?? null,
    });
    return this;
  }

  setFeatureContext(opts: {
    featureVersion?: string;
    niftyChangePct?: number;
    indiaVix?: number;
    marketRegime?: string;
    regimeScore?: number;
    mlAvailable?: boolean;
  }): this {
    Object.assign(this.trace, {
      featureVersion: opts.featureVersion ?? null,
      niftyChangePct: opts.niftyChangePct ?? null,
      indiaVix: opts.indiaVix ?? null,
      marketRegime: opts.marketRegime ?? null,
      regimeScore: opts.regimeScore ?? null,
      mlAvailable: opts.mlAvailable ?? false,
    });
    return this;
  }

  addModelPrediction(prediction: ModelPredictionTrace): this {
    this.trace.modelPredictions = [...(this.trace.modelPredictions ?? []), prediction];
    return this;
  }

  setMetaDecision(opts: {
    ensembleScore?: number;
    calibrationStatus?: "CALIBRATED" | "STALE" | "UNAVAILABLE";
    abstentionTriggered?: boolean;
    abstentionReason?: string;
  }): this {
    this.trace.metaDecision = {
      ensembleScore: opts.ensembleScore ?? null,
      calibrationStatus: opts.calibrationStatus ?? "UNAVAILABLE",
      abstentionTriggered: opts.abstentionTriggered ?? false,
      abstentionReason: opts.abstentionReason ?? null,
    };
    return this;
  }

  setRiskDecision(risk: Partial<RiskDecisionTrace>): this {
    this.trace.riskDecision = {
      approved: risk.approved ?? false,
      reason: risk.reason ?? "not evaluated",
      riskScore: risk.riskScore ?? null,
      probStopHit: risk.probStopHit ?? null,
      probTargetHit: risk.probTargetHit ?? null,
      positionSizePct: risk.positionSizePct ?? null,
      portfolioUtilization: risk.portfolioUtilization ?? null,
    };
    return this;
  }

  setFinalSignal(signal: Partial<DecisionTrace["finalSignal"]>): this {
    this.trace.finalSignal = {
      direction: signal.direction ?? null,
      entry: signal.entry ?? null,
      stopLoss: signal.stopLoss ?? null,
      target: signal.target ?? null,
      confidence: signal.confidence ?? null,
      reason: signal.reason ?? "HEURISTIC_SIGNAL",
      strategyId: signal.strategyId ?? null,
    };
    return this;
  }

  setOrderId(orderId: string): this {
    this.trace.orderId = orderId;
    return this;
  }

  build(): DecisionTrace {
    return this.trace as DecisionTrace;
  }
}

// ─── Explainability formatter ─────────────────────────────────────────────────

/**
 * Format a decision trace as a human-readable explanation.
 * This is what GET /api/trades/{id}/explain returns.
 */
export function formatTradeExplanation(trace: DecisionTrace): {
  summary: string;
  whyTaken: string;
  dataQuality: string;
  mlContribution: string;
  riskDecision: string;
  auditTrail: string[];
} {
  const signal = trace.finalSignal;
  const risk = trace.riskDecision;

  const summary =
    signal.direction
      ? `${signal.direction} trade on ${trace.correlationId ?? "unknown"} ` +
        `[${signal.strategyId ?? "strategy unknown"}] @ ${signal.entry?.toFixed(2) ?? "N/A"}`
      : "No signal generated";

  const whyTaken = buildWhyTaken(trace);
  const dataQualitySummary = buildDataQualitySummary(trace);
  const mlContribution = buildMlContribution(trace);
  const riskDecisionSummary = `Risk: ${risk.approved ? "APPROVED" : "REJECTED"} — ${risk.reason}`;

  const auditTrail: string[] = [
    `[${trace.decidedAt}] Decision trace: ${trace.decisionTraceId}`,
    `Provider: ${trace.provider ?? "unknown"} (${trace.providerHealth ?? "unknown"})`,
    `Data quality: ${trace.dataQuality}`,
    `ML available: ${trace.mlAvailable}`,
    `Regime: ${trace.marketRegime ?? "unknown"} (score: ${trace.regimeScore?.toFixed(2) ?? "N/A"})`,
    `Models: ${trace.modelPredictions.map((m) => `${m.modelName}=${m.prediction}`).join(", ") || "none"}`,
    `Meta calibration: ${trace.metaDecision.calibrationStatus}`,
    `Risk decision: ${risk.approved ? "APPROVED" : "REJECTED"} (${risk.reason})`,
    `Order ID: ${trace.orderId ?? "not created"}`,
    `Paper mode: ${trace.paperMode ? "YES" : "NO"}`,
  ];

  return { summary, whyTaken, dataQuality: dataQualitySummary, mlContribution, riskDecision: riskDecisionSummary, auditTrail };
}

function buildWhyTaken(trace: DecisionTrace): string {
  const signal = trace.finalSignal;
  if (!signal.direction) return "No trade was taken.";

  const parts: string[] = [];
  if (signal.reason === "ML_SIGNAL") {
    parts.push("ML models generated a signal");
  } else if (signal.reason === "HEURISTIC_SIGNAL") {
    parts.push("Rule-based heuristic generated the signal");
  } else if (signal.reason === "FALLBACK_SIGNAL") {
    parts.push("ML unavailable; heuristic fallback used");
  }

  if (trace.marketRegime) {
    parts.push(`market regime: ${trace.marketRegime}`);
  }
  if (trace.regimeScore !== null) {
    parts.push(`regime score: ${trace.regimeScore.toFixed(2)}`);
  }

  return parts.join(", ") || "Unknown reason.";
}

function buildDataQualitySummary(trace: DecisionTrace): string {
  const parts = [`Feature data: ${trace.dataQuality}`];
  if (trace.optionChainQuality) {
    parts.push(`Option chain: ${trace.optionChainQuality}`);
  }
  if (trace.provider) {
    parts.push(`Provider: ${trace.provider}`);
  }
  return parts.join(" | ");
}

function buildMlContribution(trace: DecisionTrace): string {
  if (!trace.mlAvailable) return "ML service unavailable — heuristic fallback used.";
  if (trace.modelPredictions.length === 0) return "No ML model predictions made.";

  const summaries = trace.modelPredictions.map(
    (m) =>
      `${m.modelName} v${m.modelVersion}: prediction=${m.prediction}, ` +
      `confidence=${m.confidence?.toFixed(2) ?? "N/A"}, ` +
      `quality=${m.dataQuality}`,
  );

  return summaries.join("; ");
}
