"""
Phase 3L — Off-policy evaluation (OPE) with uncertainty (spec §32, §33, §34).

Offline RL is NOT evaluated by naive historical replay alone (spec §32). This
module estimates the value of a target policy from trajectories generated by a
behavior policy, using standard OPE estimators, and reports uncertainty so an
unreliable estimate is flagged rather than trusted:

  - Per-decision Importance Sampling (IS)
  - Weighted Importance Sampling (WIS)
  - Doubly Robust (DR) using a fitted Q model as the control variate
  - Fitted-Q Evaluation (FQE) direct value estimate

Uncertainty (spec §33): effective sample size (ESS), coverage, importance-weight
concentration, and a bootstrap confidence interval. If the estimate is
unreliable (tiny ESS / concentrated weights / poor coverage), the status is
`OPE_INSUFFICIENT_EVIDENCE` (spec §33) — we do NOT report a point estimate as if
it were trustworthy.

The behavior policy is assumed stochastic with an epsilon-smoothed action
distribution derived from the logged behavior (deterministic baselines are
epsilon-smoothed so importance ratios are finite and well-defined).

Determinism: no np.random.* except a seeded Generator for the bootstrap CI.
"""

from __future__ import annotations

from collections import defaultdict
from dataclasses import dataclass, field
from typing import Optional

import numpy as np

from .schemas import Transition, OPEStatus
from .offline import _discretize


# ══════════════════════════════════════════════════════════════════════════════
# Policy action-probability models (epsilon-smoothed, well-defined ratios)
# ══════════════════════════════════════════════════════════════════════════════

@dataclass
class EmpiricalBehaviorPolicy:
    """
    Behavior action distribution estimated from logged data per binned state,
    epsilon-smoothed so every action has non-zero probability (finite IS ratios).
    """
    n_actions: int = 5
    bins:      int = 4
    epsilon:   float = 0.05
    _counts:   dict = field(default_factory=lambda: defaultdict(lambda: None))

    def fit(self, transitions: list[Transition]) -> "EmpiricalBehaviorPolicy":
        counts: dict = {}
        for tr in transitions:
            s = _discretize(tr.observation, self.bins)
            if s not in counts:
                counts[s] = np.zeros(self.n_actions)
            counts[s][tr.action] += 1.0
        self._counts = counts
        return self

    def prob(self, obs: list[float], action: int) -> float:
        s = _discretize(obs, self.bins)
        c = self._counts.get(s)
        if c is None or c.sum() == 0:
            return 1.0 / self.n_actions            # unseen state → uniform
        p = (c + self.epsilon) / (c.sum() + self.epsilon * self.n_actions)
        return float(p[action])


def greedy_target_prob(agent, obs: list[float], action: int, epsilon: float = 0.05) -> float:
    """
    Epsilon-greedy probability the target agent takes `action` at `obs`. The
    greedy action gets 1-eps+eps/n; others eps/n. Epsilon-smoothing keeps DR/IS
    well-defined and reflects deployment-time OOD abstention.
    """
    q = np.asarray(agent.q_values(obs), dtype=float)
    n = len(q)
    greedy = int(np.argmax(q))
    if action == greedy:
        return (1.0 - epsilon) + epsilon / n
    return epsilon / n


# ══════════════════════════════════════════════════════════════════════════════
# OPE result
# ══════════════════════════════════════════════════════════════════════════════

@dataclass
class OPEResult:
    status:            str            # OPEStatus value
    is_estimate:       Optional[float]
    wis_estimate:      Optional[float]
    dr_estimate:       Optional[float]
    fqe_estimate:      Optional[float]
    effective_sample_size: float
    n_episodes:        int
    weight_concentration: float       # max normalized weight (1=all mass on one episode)
    coverage:          float          # fraction of steps in seen states
    ci_low:            Optional[float]
    ci_high:           Optional[float]
    notes:             str = ""

    def to_dict(self) -> dict:
        return self.__dict__.copy()


# ══════════════════════════════════════════════════════════════════════════════
# Episode grouping
# ══════════════════════════════════════════════════════════════════════════════

def _split_episodes(transitions: list[Transition]) -> list[list[Transition]]:
    episodes, cur = [], []
    for tr in transitions:
        cur.append(tr)
        if tr.done:
            episodes.append(cur)
            cur = []
    if cur:
        episodes.append(cur)
    return episodes


# ══════════════════════════════════════════════════════════════════════════════
# OPE
# ══════════════════════════════════════════════════════════════════════════════

def evaluate_policy(
    transitions: list[Transition],
    agent,
    behavior: EmpiricalBehaviorPolicy,
    gamma: float = 0.99,
    target_epsilon: float = 0.05,
    min_ess: float = 5.0,
    max_weight_concentration: float = 0.5,
    min_coverage: float = 0.3,
    bootstrap_seed: int = 1337,
    n_bootstrap: int = 200,
) -> OPEResult:
    """
    Estimate the target agent's value via IS / WIS / DR / FQE with uncertainty.

    Returns OPE_INSUFFICIENT_EVIDENCE when the importance-sampling estimators are
    not trustworthy (ESS too small, weights too concentrated, or coverage poor).
    In that regime the IS/WIS/DR point estimates are still returned for
    transparency but the STATUS warns they are unreliable (spec §33).
    """
    episodes = _split_episodes(transitions)
    n_ep = len(episodes)
    if n_ep == 0:
        return OPEResult(OPEStatus.OPE_INSUFFICIENT_EVIDENCE.value, None, None, None, None,
                         0.0, 0, 1.0, 0.0, None, None, "no episodes")

    # per-episode cumulative importance weight + discounted return
    ep_weights, ep_returns, ep_dr = [], [], []
    seen_steps = 0
    total_steps = 0
    for ep in episodes:
        rho = 1.0
        G = 0.0
        dr = 0.0
        discount = 1.0
        # DR recursive term uses the fitted Q as a baseline
        for tr in ep:
            pb = behavior.prob(tr.observation, tr.action)
            pt = greedy_target_prob(agent, tr.observation, tr.action, target_epsilon)
            step_ratio = pt / pb if pb > 0 else 0.0
            rho *= step_ratio
            G += discount * tr.reward
            # DR increment: rho * (r + gamma*V(s') - Q(s,a)) + V(s)
            q_sa = float(np.asarray(agent.q_values(tr.observation))[tr.action])
            v_next = float(np.max(agent.q_values(tr.next_observation))) if not tr.done else 0.0
            v_s = float(np.max(agent.q_values(tr.observation)))
            dr += discount * (rho * (tr.reward + gamma * v_next - q_sa) + v_s * (1.0 if discount == 1.0 else 0.0))
            discount *= gamma
            total_steps += 1
            # coverage: state seen in behavior data?
            if behavior._counts.get(_discretize(tr.observation, behavior.bins)) is not None:
                seen_steps += 1
        ep_weights.append(rho)
        ep_returns.append(G)
        ep_dr.append(dr)

    w = np.array(ep_weights, dtype=float)
    g = np.array(ep_returns, dtype=float)
    dr_arr = np.array(ep_dr, dtype=float)

    # IS and WIS
    is_est = float(np.mean(w * g)) if n_ep else None
    w_sum = float(np.sum(w))
    wis_est = float(np.sum(w * g) / w_sum) if w_sum > 0 else None
    dr_est = float(np.mean(dr_arr)) if n_ep else None

    # FQE: mean of V(initial state) over episodes (direct method)
    fqe_vals = [float(np.max(agent.q_values(ep[0].observation))) for ep in episodes]
    fqe_est = float(np.mean(fqe_vals)) if fqe_vals else None

    # uncertainty diagnostics
    if w_sum > 0:
        w_norm = w / w_sum
        ess = float(1.0 / np.sum(w_norm ** 2)) if np.sum(w_norm ** 2) > 0 else 0.0
        weight_conc = float(np.max(w_norm))
    else:
        ess = 0.0
        weight_conc = 1.0
    coverage = seen_steps / total_steps if total_steps else 0.0

    # bootstrap CI on WIS (seeded)
    ci_low = ci_high = None
    if n_ep >= 2 and w_sum > 0:
        rng = np.random.default_rng(bootstrap_seed)
        boot = []
        for _ in range(n_bootstrap):
            idx = rng.integers(0, n_ep, size=n_ep)
            bw = w[idx]; bg = g[idx]
            s = bw.sum()
            if s > 0:
                boot.append(float((bw * bg).sum() / s))
        if boot:
            ci_low = float(np.percentile(boot, 2.5))
            ci_high = float(np.percentile(boot, 97.5))

    reliable = (ess >= min_ess and weight_conc <= max_weight_concentration
                and coverage >= min_coverage)
    status = OPEStatus.RELIABLE.value if reliable else OPEStatus.OPE_INSUFFICIENT_EVIDENCE.value
    notes = "" if reliable else (
        f"unreliable: ess={ess:.2f}(<{min_ess}) or weight_conc={weight_conc:.2f}(>{max_weight_concentration}) "
        f"or coverage={coverage:.2f}(<{min_coverage}); treat estimates as INSUFFICIENT_EVIDENCE (spec §33)."
    )

    return OPEResult(
        status=status, is_estimate=is_est, wis_estimate=wis_est, dr_estimate=dr_est,
        fqe_estimate=fqe_est, effective_sample_size=ess, n_episodes=n_ep,
        weight_concentration=weight_conc, coverage=coverage,
        ci_low=ci_low, ci_high=ci_high, notes=notes,
    )
